name: Mathematica

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

#  schedule:
#    - cron: '0 0 * * 0'

jobs:
  mathematica:
    uses: kolosovpetro/github-latex-template/.github/workflows/build-pdf-template.yml@MATH-90
    with:
      mathematica-directory: ./mathematica
      wolfram-image: wolframresearch/wolframengine:15.0
      wolfram-scripts: |
        ValidateOrdinarySumsOfPowers.txt
        ValidateDoubleSumsOfPowers.txt
        ValidateMultifoldSumsOfPowers.txt
        ValidateMultifoldBinomialSumsOfPowers.txt
        ValidateOrdinarySumsOfPowersAtZero.txt
        ValidateDoubleSumsOfPowersAtZero.txt
        ValidateMultifoldSumsOfPowersAtZero.txt
        ValidateMultifoldSumsOfPowersAtZeroBinomialForm.txt
    secrets:
      WOLFRAM_LICENSE_FILE: ${{ secrets.WOLFRAM_LICENSE_FILE }}